require(knitr)
require(markdown)
setwd("C:/Users/User/Documents/Getting clean data/assignment_w4")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")
